services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: "python bot.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: "your-telegram-bot-token"
      - key: WEBHOOK_URL
        value: "https://your-app.onrender.com"