services:
  - type: web
    name: vpn-subscription-bot
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: TELEGRAM_TOKEN
        value: "your-telegram-bot-token"