services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        value: <your-telegram-bot-token> # 替换为实际的 Telegram Bot Token
      - key: WEBHOOK_URL
        value: https://<your-app>.onrender.com/<your-telegram-bot-token> # 替换为实际的 Webhook URL