def get_accounts(): ...
def is_ssh_connected(chat_id): ...
async def handle_ssh_output(stdout, update, timeout=10): ...
async def connect_to_host(update: Update, context: ContextTypes.DEFAULT_TYPE, host_info): ...